### ISSUE TITLE
Specific block teleport

### ISSUE THREAD

**Issue by LogGits** [XZot1K/SimplePortals#10]
Is there a way to make a spec block cause a teleport e.g. i want to do a selection that is diagonal and have only water blocks teleport a player.
```
oox
oxo
xoo
```
whereby `x` is a water block and `o` is air if they walk into air, it does nothing but if they walk into the water or (x) it teleports them.

Loving the plugin, keep up the great work ❤️

**Comment by XZot1K** [comment]
> 
> 
> Is there a way to make a spec block cause a teleport e.g. i want to do a selection that is diagonal and have only water blocks teleport a player.
> 
> ```
> oox
> oxo
> xoo
> ```
> 
> whereby `x` is a water block and `o` is air if they walk into air, it does nothing but if they walk into the water or (x) it teleports them.
> 
> Loving the plugin, keep up the great work ❤️

Currently, teleportation is only bound through bare minimum coordinate regions. Specific block teleportation is not yet avaliable, but could be implemented in the future.
