### ISSUE TITLE
Filling a portal w/ the nether_portal display works in 1 direction, but not the other.

### ISSUE THREAD

**Issue by TripleNothing** [XZot1K/SimplePortals#11]
[Example Image](http://minecraft.hellzoneinc.com/portalMaterial.png)
nether_portal material displays just fine at 1 portal, but when it is to be displayed in the rotated direction, the portals don't align when added/defined.

**Comment by XZot1K** [comment]
> 
> 
> [Example Image](http://minecraft.hellzoneinc.com/portalMaterial.png)
> nether_portal material displays just fine at 1 portal, but when it is to be displayed in the rotated direction, the portals don't align when added/defined.

This is normal. The plugin has no directional support for materials, the command was added as a simple mechanic for difficult materials like water or lava. Until directional support can be added for versions 1.8-1.15 without any inconsistent flaws, I recommend using WorldEdit for this!
