### ISSUE TITLE
(1.15.2) "previous world is null"

### ISSUE THREAD

**Issue by Falcon-one0** [XZot1K/SimplePortals#12]
When I use a portal a message appears in the chat and say "previous world is null" and I don't know what I have to do ):

**Comment by XZot1K** [comment]
> When I use a portal a message appears in the chat and say "previous world is null" and I don't know what I have to do ):

It is likely a world the portal is attempting to teleport the player to is invalid. Try using the "/portals sl <portal>" command to set the teleportation location at an existing location. This should resolve the issue. You can also attempt to re-make the portal, if needed.

**Comment by l1ghtsword** [comment]
Closing issue due to no response.
If you have any further issues, please head over to our discord for support as there is more information and resources located there. http://discord.gg/pzAsqsZ
