### ISSUE TITLE
Time until you can enter a portal shown as a negative

### ISSUE THREAD

**Issue by ExpiredMinotaur** [XZot1K/SimplePortals#14]
When trying to enter a portal withing the cooldown it shows a negative number in the message
![image](https://user-images.githubusercontent.com/1735367/79751442-7d1a2b00-830a-11ea-9068-e496431ba63c.png)

**Comment by XZot1K** [comment]
> 
> 
> When trying to enter a portal withing the cooldown it shows a negative number in the message
> ![image](https://user-images.githubusercontent.com/1735367/79751442-7d1a2b00-830a-11ea-9068-e496431ba63c.png)

Thank you for the report, i'll check it out!
