### ISSUE TITLE
Feature Request: Link Portals

### ISSUE THREAD

**Issue by hellot1m** [XZot1K/SimplePortals#16]
Would be awesome if you were able to link two portals together, expanding on an already existing command `/portal setlocation portal1 portal2` with both created portals listed together, this command would simply just connect the two portals. or a new command `/portal bind portal1 portal2` or instead of bind you could use `link` `bindportals` `connect`.

**Comment by XZot1K** [comment]
This feature has been added alongside a really nice linking check!
