### ISSUE TITLE
Feature Request: Separate message to each individual portal + Title/subtitle/actionbar message 

### ISSUE THREAD

**Issue by momoahdev** [XZot1K/SimplePortals#17]
Hello, i like your plugin so much , thanks for your helping.
I would like to request to have individual portal's message and having more output options such as Title / Subtitle / Action bar

demo:
https://pasteboard.co/JqdR6ez.jpg

**Comment by XZot1K** [comment]
This feature has been added with full functionality!

**Comment by momoahdev** [comment]
> 
> 
> This feature has been added with full functionality!

Thanks for help. But the Bossbar message seem not work. And hope you can help to make Actionbar function , so i can save server's space no need to install the other actionbar's plugin such as : https://www.spigotmc.org/resources/actionbar.4754/
:) thanks!

**Comment by XZot1K** [comment]
There you go I resolved it!
