### ISSUE TITLE
[BUG] When lang.yml changes nothing changes

### ISSUE THREAD

**Issue by mani1232** [XZot1K/SimplePortals#18]
**Describe the bug**

Changing portal-message: "" does not change anything

**To Reproduce**
Steps to reproduce the bug:
-

**Expected behavior**

Delete or change text

**Screenshots & Other Media**
-

**Server Information (Please fill in the information below):**
 - Version: 1.16.3
 - Plugins: Essentials, Vault, and more

**Additional context**
-

**Comment by mani1232** [comment]
portal-title-message: ""
portal-subtitle-message: ""
portal-bar-message: ""

**Comment by XZot1K** [comment]
> **Describe the bug**
> 
> Changing portal-message: "" does not change anything
> 
> ## **To Reproduce**
> Steps to reproduce the bug:
> **Expected behavior**
> 
> Delete or change text
> 
> ## **Screenshots & Other Media**
> **Server Information (Please fill in the information below):**
> 
> * Version: 1.16.3
> * Plugins: Essentials, Vault, and more
> 
> ## **Additional context**

These messages are individual for each and every portal. It’s used as a default; therefore, already made portals will still have their original messages if those were changed after that portal creation. If the server is offline, plugin is disabled, or the command is used, then these messages can be individually set to empty!

**Comment by XZot1K** [comment]
I added more information to resource page on this. Please refer to the FAQ there for a quick fix!
