### ISSUE TITLE
Message Speed [REQUEST]

### ISSUE THREAD

**Issue by hellot1m** [XZot1K/SimplePortals#19]
**In a couple of words, describe the feature you'd like to see:**
Love the new message feature per portal. But could you add duration options in the portals config.  

**Screenshots & Media**
This screen snip is from [minecraft.tools](https://minecraft.tools/en/title.php)
![image](https://user-images.githubusercontent.com/51469357/93437976-7e339200-f881-11ea-99ac-92c7e8db8da2.png)

**Additional context**
Layout similar to this, can be seconds, tics, whatever is easier, this is just an example of what the config would look like under each portal for the title messages. 
```
#Time is in seconds
     Duration: `5`
     Fade In: `1`
     Fade Out: `1`
```

**Comment by XZot1K** [comment]
> **In a couple of words, describe the feature you'd like to see:**
> Love the new message feature per portal. But could you add duration options in the portals config.
> 
> **Screenshots & Media**
> This screen snip is from [minecraft.tools](https://minecraft.tools/en/title.php)
> ![image](https://user-images.githubusercontent.com/51469357/93437976-7e339200-f881-11ea-99ac-92c7e8db8da2.png)
> 
> **Additional context**
> Layout similar to this, can be seconds, tics, whatever is easier, this is just an example of what the config would look like under each portal for the title messages.
> 
> ```
> #Time is in seconds
>      Duration: `5`
>      Fade In: `1`
>      Fade Out: `1`
> ```

1.5 contains this feature for titles and sub-titles as a global parameter; however, this does not affect bar messages due to limitations without using tasks.
