### ISSUE TITLE
Stored portals gone missing when unloading server

### ISSUE THREAD

**Issue by donvdp** [XZot1K/SimplePortals#23]
**Explaining the issue**
about a week ago there were allot of portals that 'suddenly' disappeared. It seemd to have happend when the server was shutting down for a maintenance reboot. Everyday at 04:20 the server reboots in order to clear buffers. After searching through the server logs i found ALLOT of "Cannot load plugins/SimplePortals/portals.yml" errors in the console. I've made a [pastebin](https://pastebin.pl/view/fa878212) of it. After these errors almost all portals were gone (not all).

**To reproduce**
I cant resproduce this issues, i dont know how it happend in the first place. all i know the server was rebooting, just like its been doing every night for the last year.

**Expected behavior**
i expected the plugin to unload as normaly and NOT go corrupt..

**Screenshots & Other Media**
Ive previously posted this issue on [the spigot page](https://www.spigotmc.org/threads/1-16-ready-%E2%8D%9F-simple-portals-%E2%8D%9F-effective-regional-portals-bungeecord-compatible.319254/page-20), sorry i didnt know you used github.
- [pastebin of errors](https://pastebin.pl/view/fa878212)

**Server Information (Please fill in the information below):**
Running 
- Papermc build 282
- Simple Portals 1.5.1
all plugins are listed on [this](https://timings.aikar.co/?id=f64490136e87459abab9a9ccf7ce34c8#plugins) site.

**Additional context**
I'd like to point out that we have been using simple portals for about a year now. This is the 3rth time this has happend and im not able to correlate the incidences. We are rebooting our servers every night. and appart from the 3 times the portals plugin got corrupted there have not been issues. We are however starting to use it less and less because we cant depend on it not getting corrupt. using commandblocks now it our way of working arround the issue of portal corruptions.

**Comment by XZot1K** [comment]
> **Explaining the issue**
> about a week ago there were allot of portals that 'suddenly' disappeared. It seemd to have happend when the server was shutting down for a maintenance reboot. Everyday at 04:20 the server reboots in order to clear buffers. After searching through the server logs i found ALLOT of "Cannot load plugins/SimplePortals/portals.yml" errors in the console. I've made a [pastebin](https://pastebin.pl/view/fa878212) of it. After these errors almost all portals were gone (not all).
> 
> **To reproduce**
> I cant resproduce this issues, i dont know how it happend in the first place. all i know the server was rebooting, just like its been doing every night for the last year.
> 
> **Expected behavior**
> i expected the plugin to unload as normaly and NOT go corrupt..
> 
> **Screenshots & Other Media**
> Ive previously posted this issue on [the spigot page](https://www.spigotmc.org/threads/1-16-ready-%E2%8D%9F-simple-portals-%E2%8D%9F-effective-regional-portals-bungeecord-compatible.319254/page-20), sorry i didnt know you used github.
> 
> * [pastebin of errors](https://pastebin.pl/view/fa878212)
> 
> **Server Information (Please fill in the information below):**
> Running
> 
> * Papermc build 282
> * Simple Portals 1.5.1
>   all plugins are listed on [this](https://timings.aikar.co/?id=f64490136e87459abab9a9ccf7ce34c8#plugins) site.
> 
> **Additional context**
> I'd like to point out that we have been using simple portals for about a year now. This is the 3rth time this has happend and im not able to correlate the incidences. We are rebooting our servers every night. and appart from the 3 times the portals plugin got corrupted there have not been issues. We are however starting to use it less and less because we cant depend on it not getting corrupt. using commandblocks now it our way of working arround the issue of portal corruptions.

This actually looks like the portal messages causing the issue, I have adjusted the message to blank in the latest update which should allow users with a newly generated config.yml to avoid having messages attached to portals created beyond that point. The errors you have attached are due to a quote not formatting into the data file correctly which causes a domino effect upon all portals within the loading process. 

I have adjustments in process which will further evaluate this issue, but until then that information above should help you out a little bit! I apologize for the inconvenience you experienced in the past and hopefully that information provided will better the future experience alongside this upcoming update!

**Comment by donvdp** [comment]
ive checked the backups and no portals have custom messaged attatched to them.  (see attatcked portals.yml file from my backup).. we did however disable a few messaged with ingame command "/portals disablemessages <portalname>" and i see in the config that this causes the "message" variable to be empty. maybe that is causing the issue?

Ive also included the portals.yml file that is left over after the cascading effect, maybe this can help you a little.... im doing what i can. if you need anything else let me know. im willing to help.

backup file:  https://we.tl/t-RAD2geYrkp
leftover file after cascase failure:  https://we.tl/t-QouL2jsWWe

**Comment by XZot1K** [comment]
> ive checked the backups and no portals have custom messaged attatched to them. (see attatcked portals.yml file from my backup).. we did however disable a few messaged with ingame command "/portals disablemessages " and i see in the config that this causes the "message" variable to be empty. maybe that is causing the issue?
> 
> Ive also included the portals.yml file that is left over after the cascading effect, maybe this can help you a little.... im doing what i can. if you need anything else let me know. im willing to help.
> 
> backup file: https://we.tl/t-RAD2geYrkp
> leftover file after cascase failure: https://we.tl/t-QouL2jsWWe

Would you mind joining my Discord? I have a sample build for the new data structure which I need someone to try out before I branch this out. I have a discord invite link on the left side at https://www.zotware.dev/!
