### ISSUE TITLE
Deleting non-existent portal creates CONSOLE spam. [BUG]

### ISSUE THREAD

**Issue by audion64** [XZot1K/SimplePortals#24]
Pretty minor but I figured you should know. Using "/portals delete <PortalName>"  where PortalName is a name that does not exist (due to typo or whatever) creates tons of Info level CONSOLE spam.
------------------------------------------------------------------------------------------
ERROR null
29.12 00:36:00 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'portals' in plugin SimplePortals v1.5.3
29.12 00:36:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2006) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1817) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1770) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
29.12 00:36:00 [Server] INFO Caused by: java.lang.NullPointerException
29.12 00:36:00 [Server] INFO at xzot1k.plugins.sp.core.Commands.initiatePortalDeletion(Commands.java:713) ~[?:?]
29.12 00:36:00 [Server] INFO at xzot1k.plugins.sp.core.Commands.onCommand(Commands.java:87) ~[?:?]
29.12 00:36:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-324]
29.12 00:36:00 [Server] INFO ... 19 more

**Comment by XZot1K** [comment]
> ## Pretty minor but I figured you should know. Using "/portals delete " where PortalName is a name that does not exist (due to typo or whatever) creates tons of Info level CONSOLE spam.
> ERROR null
> 29.12 00:36:00 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'portals' in plugin SimplePortals v1.5.3
> 29.12 00:36:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2006) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1817) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1770) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
> 29.12 00:36:00 [Server] INFO Caused by: java.lang.NullPointerException
> 29.12 00:36:00 [Server] INFO at xzot1k.plugins.sp.core.Commands.initiatePortalDeletion(Commands.java:713) ~[?:?]
> 29.12 00:36:00 [Server] INFO at xzot1k.plugins.sp.core.Commands.onCommand(Commands.java:87) ~[?:?]
> 29.12 00:36:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-324]
> 29.12 00:36:00 [Server] INFO ... 19 more

The next update attempts to resolve this, if your issue, in particular, re-occurs please don't hesitate to re-open this issue or create a new pull :)
