### ISSUE TITLE
Allow OPs to see and/or teleport to portal locations. [REQUEST]

### ISSUE THREAD

**Issue by audion64** [XZot1K/SimplePortals#25]
After creating dozens of portals on my server I realized I had no easy way of know WHERE they are located.  "/portals list" shows them by name but no idea where they are located.  I see that each portal gets its own .yml file created and the coords are listed there but to manually look in each file is not user friendly.

Allowing OPs to either do the list command and have it show the coords for all listed portals or, a separate "/portals view <name> command to view ALL the data about an individual portal (message, commands attached, coords, etc).  Maybe even have a built in TP command that allows OPs to direct TP to where the portal is located.

Thanks for a great plugin!

**Comment by XZot1K** [comment]
> After creating dozens of portals on my server I realized I had no easy way of know WHERE they are located. "/portals list" shows them by name but no idea where they are located. I see that each portal gets its own .yml file created and the coords are listed there but to manually look in each file is not user friendly.
> 
> Allowing OPs to either do the list command and have it show the coords for all listed portals or, a separate "/portals view command to view ALL the data about an individual portal (message, commands attached, coords, etc). Maybe even have a built in TP command that allows OPs to direct TP to where the portal is located.
> 
> Thanks for a great plugin!

The next update will have a temporary solution that will replace the current feature with a full listing mechanic providing averaged out region coordinates and displayed in RED or GREEN based on enabled/disabled portals. In the future, I will adjust accordingly to found issues and also possibly implement clickable JSON features with teleportation!
