### ISSUE TITLE
/simpleportals addcommand <name> <command>:PLAYER doesn't work

### ISSUE THREAD

**Issue by HappyHippo77** [XZot1K/SimplePortals#28]
Maybe I'm just misunderstanding the syntax, but instead of running this how I understand it's supposed to, it seems to just run "/command:PLAYER" as if it was just typed in exactly like that. I'm using BungeeCord and EssentialsX and those are the only things I can think of that would mess up something like this.

**Comment by XZot1K** [comment]
> 
> 
> Maybe I'm just misunderstanding the syntax, but instead of running this how I understand it's supposed to, it seems to just run "/command:PLAYER" as if it was just typed in exactly like that. I'm using BungeeCord and EssentialsX and those are the only things I can think of that would mess up something like this.

If the command is a true command, then proper syntax will be "/portals addcmd command:PLAYER" in that case. For fake commands (event based) use :CHAT instead!

**Comment by XZot1K** [comment]
I had a typo in that command I referenced above! Let me know if that helps :)
