### ISSUE TITLE
Issue when upgrading to SP from that other portal plugin Multiverse. Portals

### ISSUE THREAD

**Issue by EchocallingEarth** [XZot1K/SimplePortals#3]
Not sure if this is a issue with Simpleportals replacing a portal plugin or a issue with SimplePortals and something that should be set and we missed. 
We updated to Simple Portals as it is far superior and also works with FAWE and many other plugins we already use. Previously we had that Multiverse Portals plugin and well earned our lesson of how great Simpleportals is. However now all of our nether and end portals are failing. If we attempt to use one the server crashes. I attempted to research the matter but found very little about it. After much research I decided that perhaps the Dev  may have a solution.

**Comment by XZot1K** [comment]
> Not sure if this is a issue with Simpleportals replacing a portal plugin or a issue with SimplePortals and something that should be set and we missed.
> We updated to Simple Portals as it is far superior and also works with FAWE and many other plugins we already use. Previously we had that Multiverse Portals plugin and well earned our lesson of how great Simpleportals is. However now all of our nether and end portals are failing. If we attempt to use one the server crashes. I attempted to research the matter but found very little about it. After much research I decided that perhaps the Dev may have a solution.

This is an interesting report. I just ran a small test to see if I could in some way replicate this and failed, but I do want to mention that portal teleportation from End Portals and Nether Portals are canceled while within a Simple Portal region. Other than the event being canceled, vanilla portals are practically untouched. This shouldn't cause a crash either even if simple portals did have an issue with this. At worst I would imagine teleportation to the nether or end would simply not work and just idle the player in the portal, but this doesn't seem to be the case. Keep me up to date with this and I will explore some more as well in case I find something on my end!
