### ISSUE TITLE
[BUG] API Initilization

### ISSUE THREAD

**Issue by synexTG** [XZot1K/SimplePortals#30]
**Describe the bug**
I did the described implementation on the front page but this happens:
![c7df63943f62](https://user-images.githubusercontent.com/36425229/127750150-95cd1865-cfc5-4ef8-9c37-114e390497f2.png)

Exact implementation:
```
package de.synex.factioncontroller;

import xzot1k.plugins.sp.SimplePortals;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.Bukkit;


public final class FactionController extends JavaPlugin {

     private static SimplePortals simplePortals;

    @Override
    public void onEnable() {
        // Plugin startup logic
        if (!isSimplePortalsInstalled())
        {
            getServer().getPluginManager().disablePlugin(this);

            return;
        }
        getServer().getPluginManager().registerEvents(new PortalEnterListener(this), this);
        System.out.println("FactionController enabled");
    }

    private boolean isSimplePortalsInstalled() {
        SimplePortals simplePortals = (SimplePortals) getServer().getPluginManager().getPlugin("SimplePortals");

        if(simplePortals != null)
        {
            setSimplePortals(simplePortals);
            return true;
        }

        return false;
    }

	@Override
    public void onDisable() {
        // Plugin shutdown logic
        System.out.println("FactionController disabled");
    }

    public static SimplePortals getSimplePortals() {
        return simplePortals;
    }

    private static void setSimplePortals(SimplePortals simplePortals) { FactionController.simplePortals = simplePortals; }
}
```

**To Reproduce**
Steps to reproduce the bug:
1. Install SimplePortals on Paper 1.17.1.
2. Create an own plugin with the dependency "SimplePortals" and do the implementation like mentioned on the main page here.
3. Start Server & See result.

**Expected behavior**
No Errors and PortalEnterEvent shoudl be executed?
I can't test the listener:
```
public class PortalEnterListener implements Listener {

    FactionController main;

    public PortalEnterListener(FactionController pl) {
        main = pl;
    }

    @EventHandler
    public void onPortalEnter(PortalEnterEvent e) {
    }
}
```

**Screenshots & Other Media**
![c7df63943f62](https://user-images.githubusercontent.com/36425229/127750150-95cd1865-cfc5-4ef8-9c37-114e390497f2.png)

**Server Information (Please fill in the information below):**
 - Version: git-Paper-127 (MC: 1.17.1)
 - Plugins: SimplePortals and custom plugin like mentioned

**Comment by XZot1K** [comment]
> **Describe the bug**
> I did the described implementation on the front page but this happens:
> ![c7df63943f62](https://user-images.githubusercontent.com/36425229/127750150-95cd1865-cfc5-4ef8-9c37-114e390497f2.png)
> 
> Exact implementation:
> 
> ```
> package de.synex.factioncontroller;
> 
> import xzot1k.plugins.sp.SimplePortals;
> import org.bukkit.plugin.java.JavaPlugin;
> import org.bukkit.Bukkit;
> 
> 
> public final class FactionController extends JavaPlugin {
> 
>      private static SimplePortals simplePortals;
> 
>     @Override
>     public void onEnable() {
>         // Plugin startup logic
>         if (!isSimplePortalsInstalled())
>         {
>             getServer().getPluginManager().disablePlugin(this);
> 
>             return;
>         }
>         getServer().getPluginManager().registerEvents(new PortalEnterListener(this), this);
>         System.out.println("FactionController enabled");
>     }
> 
>     private boolean isSimplePortalsInstalled() {
>         SimplePortals simplePortals = (SimplePortals) getServer().getPluginManager().getPlugin("SimplePortals");
> 
>         if(simplePortals != null)
>         {
>             setSimplePortals(simplePortals);
>             return true;
>         }
> 
>         return false;
>     }
> 
> 	@Override
>     public void onDisable() {
>         // Plugin shutdown logic
>         System.out.println("FactionController disabled");
>     }
> 
>     public static SimplePortals getSimplePortals() {
>         return simplePortals;
>     }
> 
>     private static void setSimplePortals(SimplePortals simplePortals) { FactionController.simplePortals = simplePortals; }
> }
> ```
> 
> **To Reproduce**
> Steps to reproduce the bug:
> 
> 1. Install SimplePortals on Paper 1.17.1.
> 2. Create an own plugin with the dependency "SimplePortals" and do the implementation like mentioned on the main page here.
> 3. Start Server & See result.
> 
> **Expected behavior**
> No Errors and PortalEnterEvent shoudl be executed?
> I can't test the listener:
> 
> ```
> public class PortalEnterListener implements Listener {
> 
>     FactionController main;
> 
>     public PortalEnterListener(FactionController pl) {
>         main = pl;
>     }
> 
>     @EventHandler
>     public void onPortalEnter(PortalEnterEvent e) {
>     }
> }
> ```
> 
> **Screenshots & Other Media**
> ![c7df63943f62](https://user-images.githubusercontent.com/36425229/127750150-95cd1865-cfc5-4ef8-9c37-114e390497f2.png)
> 
> **Server Information (Please fill in the information below):**
> 
> * Version: git-Paper-127 (MC: 1.17.1)
> * Plugins: SimplePortals and custom plugin like mentioned

Hey there, I appreciate the report! There seems to have been some issues involving how casting was done in the example. I updated the example with the following:
`import org.bukkit.plugin.java.JavaPlugin;
import xzot1k.plugins.sp.SimplePortals;

public class Main extends JavaPlugin {

    private SimplePortals simplePortals;

    @Override
    public void onEnable() {
        if (!isSimplePortalsInstalled()) {
            getServer().getPluginManager().disablePlugin(this); // disable plugin since SimplePortals is NOT installed.
            return;
        }

        // SimplePortals was found and now can be accessed with the getSimplePortals() getter.
    }

    // This method tells you whether SimplePortals is installed or not.
    private boolean isSimplePortalsInstalled() {
        if (getServer().getPluginManager().getPlugin("SimplePortals") != null)
            this.simplePortals = SimplePortals.getPluginInstance();
        return false;
    }

    public SimplePortals getSimplePortals() { return simplePortals; }

}`

**Comment by synexTG** [comment]
Hey thanks for helping out.

Now i am getting the following error:
`[02:19:13 ERROR]: Ambiguous plugin name `SimplePortals' for files `plugins/de.synex.factioncontroller-1.0-SNAPSHOT-jar-with-dependencies.jar' and `plugins/SimplePortals.jar' in `plugins'`

**Comment by synexTG** [comment]
Okay i got it working, i forgot the maven scope "provided". I will now test the PortalEnterEvent and if this works i will close the issue.

**Comment by synexTG** [comment]
Nice its working now, thank you :)
