### ISSUE TITLE
Create a portal "cooldown" like a nether portal to teleport.

### ISSUE THREAD

**Issue by Apprisco** [XZot1K/SimplePortals#31]
**In a couple of words, describe the feature you'd like to see:**
I hate it when I touch the portal and am immediately teleported. I want to use this as an alternative in a technical base, but I can't because the teleport is immediate. It'd be a great plugin if there was a load time, like 3 seconds, before you are teleported.

**Comment by AlessioGr** [comment]
@CoderStone Added with https://github.com/XZot1K/SimplePortals/commit/ae12765536168062fce680700f497b40b7dca3c5 but not yet released. You can test it early with this version, if you want to: https://ufile.io/6xrr69vk

Tell me what you think :)
