### ISSUE TITLE
[BUG] Teleportation with vanilla portals (1.6.9)

### ISSUE THREAD

**Issue by aurel85** [XZot1K/SimplePortals#32]
Hi,

As of 1.6.9 my players can no longer teleport through nether and end vanilla portals which are heavily used on my skyblock. Other entities (mobs) can, but not them. Is there a setting to make or another solution because on my Survival and Creative server I don't use vanilla portals but in Skyblock it's different.
With SimplePortals in 1.6.8, everything works.

I am using Paper 1.18.1.

Thank you in advance.

**Comment by charlyg31** [comment]
https://github.com/BentoBoxWorld/BentoBox/issues/1939

**Comment by editon96** [comment]
I can say that that dont be only Skyblock that is eather for normal Vanilla. 
It dont work.

Nether and End Portals dont work

**Comment by XZot1K** [comment]
This should have been resolved a while back. Please reopen this issue, if the issue persists.
