### ISSUE TITLE
Nether portals getting blocked

### ISSUE THREAD

**Issue by adelando** [XZot1K/SimplePortals#33]
Hi, I have simpleportals version ( 1.6.9 )  installed on my server

server software is git-purpur-1566 (MC-1.18.1)

When i disable the plugin nether portals work, but with the plugin enabled they dont work and wont teleport you to the nether (or overworld)

Also Multiverse-core version (4.3.1-b861)

**Comment by XZot1K** [comment]
This should have been resolved a long time ago. Please reopen and keep me posted if the issue still occurs for you instance.
