### ISSUE TITLE
[BUG] Trojan infect?

### ISSUE THREAD

**Issue by nanana90** [XZot1K/SimplePortals#49]
=>xzot1k/plugins/sp/api/enums/PortalCommandType.class ist mit Java.Trojan.GenericGBA.35077 infiziert

**Comment by nanana90** [comment]
the download are infected!

**Comment by XZot1K** [comment]
> the download are infected!

Java.Trojan.GenericGBA is a false positive flagged by windows defender. It occasionally occurs when reflection is used and maven builds the jar. Not every system flags it either, but will be looked into more
