### ISSUE TITLE
Can you use this for worlds?

### ISSUE THREAD

**Issue by cfanoulis** [XZot1K/SimplePortals#5]
Just a quick question, can you use this to teleport to seperate worlds?

**Comment by XZot1K** [comment]
Cross-Server and Cross-World teleportation are available. Please either use the main discussion [here](https://www.spigotmc.org/threads/1-14-2-ready-%E2%8D%9F-simple-portals-%E2%8D%9F-effective-regional-portals-bungeecoord-compatible.319254/), contact me directly at alexosborne54@gmail.com, or on discord at XZot1K#7490 for questions. I'd prefer the GitHub issues page to be for issues only!

**Comment by XZot1K** [comment]
[](url)
