### ISSUE TITLE
"All Portals have been saved" Causing large uptick

### ISSUE THREAD

**Issue by Buzzbugs** [XZot1K/SimplePortals#6]
Hello, we're having an issue. I have taken a screenshot. Might there be way to turn off this automatic saving?

![high tick rate](https://user-images.githubusercontent.com/54085800/63402949-9f2c7800-c420-11e9-8098-388fe7e7d622.jpg)

Thank you all the best.

**Comment by XZot1K** [comment]
To disable the auto-save feature set the global task delay in the configuration to -1!

**Comment by Buzzbugs** [comment]
Hello,

I cannot see this setting in the config. This is the closest thing that resembles it
![global](https://user-images.githubusercontent.com/54085800/63425614-51316780-c454-11e9-8a5e-341a29235f5b.jpg)

**Comment by XZot1K** [comment]
That's the one! That should only affect a couple of things, but generally, it's saving features.

**Comment by Buzzbugs** [comment]
this solved my issue. thank you :)
