### ISSUE TITLE
Issue with 1.8 ---> 1.14 Portal

### ISSUE THREAD

**Issue by Buzzbugs** [XZot1K/SimplePortals#8]
Hello,

This is an issue I am having between a 1.8 and a 1.14 server.

Portaling from the 1.14 ----> to the 1.8 server works fine.

But Portaling back the other way does not work, and produces this error in the log.

Any help would be greatly appreciated!

https://pastebin.com/9WUMejqB

**Comment by XZot1K** [comment]
This is a configuration issue on the 1.8 server. Simply change the "ENTITY_GHAST_SHOOT" sound in the config to "" or a valid id.
